### ISSUE TITLE
ModuleNotFoundError: No module named 'ConfigParser'

### ISSUE THREAD

**Issue by stellargo** [o-d-i-n/HelloWorld#31]
While initial setup on running install via requirements.txt, following error comes up:
```
 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-efk_0ceg/MySQL-python/setup.py", line 13, in <module>
        from setup_posix import get_config
      File "/private/tmp/pip-build-efk_0ceg/MySQL-python/setup_posix.py", line 2, in <module>
        from ConfigParser import SafeConfigParser
    ModuleNotFoundError: No module named 'ConfigParser'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-efk_0ceg/MySQL-python/

```
Python 3.6.2
pip 9.0.1
OS X El Capitan Version: 10.11.6 (15G1004)

**Comment by mananpal1997** [comment]
@stellargo first of all thanks for raising the issue.
MySQL-python doesn't support python 3.x and ConfigParser was renamed in python 3.x for some pep8 issue.

We'll be updating the repo to support both python versions @mbad0la 
Meanwhile, @stellargo you can run it with python 2.x

**Comment by stellargo** [comment]
Thanks a lot @mananpal1997 !
For anybody who gets stuck on this in the future:
You need to completely remove python3 (it's a little cumbersome and a mixture of a few answers on stackoverflow will work).
If you get this error:
```
Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/55/nvk5fp4159qgck608_bbl_q00000gn/T/pip-build-ggu7FF/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/55/nvk5fp4159qgck608_bbl_q00000gn/T/pip-build-ggu7FF/MySQL-python/
```
,then install mysql.

**Comment by stellargo** [comment]
@mananpal1997 Error while running
User$ python2 manage.py setup
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/User/HelloWorld/helloWorld/settings.py", line 15, in <module>
    from config import MYSQL_USERNAME, MYSQL_PASSWORD, MYSQL_HOSTNAME, MYSQL_DATABASE
ImportError: No module named config
```
Python 2.7.13
npm 3.10.8
pip 9.0.1

**Comment by mananpal1997** [comment]
@stellargo create a file named config.py in the main directory and edit it as following (you need to setup a mysql client on your system and fill in the credentials accordingly in config.py)
```
MYSQL_USERNAME = <username>
MYSQL_PASSWORD = <password>
MYSQL_HOSTNAME = root # by default
MYSQL_DATABASE = <database name>
```

And one more thing, @stellargo you don't need to remove python3, you can have two python versions working in one system :smile:

**Comment by mananpal1997** [comment]
@mbad0la I think you can close the issue now. 👍

**Comment by mbad0la** [comment]
Feel free to close the issue yourself in the future, @mananpal1997 . You don't have to ask :)
